### ISSUE TITLE
Exception throw in callback Order logic

### ISSUE THREAD

**Issue by robaimes** [AltaPay/plugin-magento2-community#142]
## Description 
The primary issue here is that [this function ](https://github.com/AltaPay/plugin-magento2-community/blob/main/Block/Callback/Ordersummary.php#L125)can return a string in cases where the `getOrderId` function returns a falsey value. The use of `->getShippingAddress()` on this when this function returns a string is throwing an exception as `getShippingAddress` is not a function attached to a string.

1. https://github.com/AltaPay/plugin-magento2-community/blob/main/Block/Callback/Ordersummary.php#L132
2. https://github.com/AltaPay/plugin-magento2-community/blob/main/Block/Callback/Ordersummary.php#L142
3. https://github.com/AltaPay/plugin-magento2-community/blob/main/Block/Callback/Ordersummary.php#L143

In cases where the `shop_orderid` parameter is not present or is a _falsey_ value, the call to `$order->getShppingAddress()` will throw an exception.

## Additional notes
This `getOrder` function has a docblock that states it can _only_ return a string. This is not the case as it would normally return an Order object.

**Comment by BushraAsif** [comment]
Thanks @robaimes, We will take a look at it and will get back to you.

**Comment by shahbaz-mehar** [comment]
@robaimes Fix available in release https://github.com/AltaPay/plugin-magento2-community/releases/tag/3.7.2
