### ISSUE TITLE
Deprecated Functionality: str_replace()

### ISSUE THREAD

**Issue by ap-bw** [AltaPay/plugin-magento2-community#180]
Getting this error when paying without telefonnumber. Running php8.1 and M2.4.6p1

 Deprecated Functionality: str_replace(): Passing null to parameter #3 ($subject) of type array|string is deprecated in /var/www/xxxxxx/public_html/vendor/altapay/magento2-community/Model/Handler/CustomerHandler.php on line 103 at /var/www/xxxxxx/public_html/lib/internal/Magento/Framework/App/ErrorHandler.php:62)"} []

**Comment by shahbaz-mehar** [comment]
@ap-bw Thanks for the heads-up! We've added a fix for this issue and this will be available in our upcoming release.

**Comment by shahbaz-mehar** [comment]
@ap-bw This has been fixed in the latest release. https://github.com/AltaPay/plugin-magento2-community/releases/tag/3.9.1
