### ISSUE TITLE
Can't select as the default payment method

### ISSUE THREAD

**Issue by maxvovk** [AltaPay/plugin-magento2-community#2]
in `/etc/config.xml`
tag <title /> don't have value -> as a result:
in options to select default payment have next code:
`<\optgroup label="Altapay">
<\option value="terminal2"></option>
<\option value="terminal5"></option>
<\option value="terminal4"></option>
<\option value="terminal3"></option>
<\option value="terminal1"></option>
<\/optgroup>`

**Comment by BushraAsif** [comment]
This issue is fixed since 3.0.0 was released.
