### ISSUE TITLE
Product stock not updating properly

### ISSUE THREAD

**Issue by elvis-zunde** [AltaPay/plugin-magento2-community#34]
**Steps to reproduce**
1. Add to cart
2. Checkout
3. Fail Payment (**stock gets returned!)**
4. Hit back button
5. Succeed payment ( same order ) **(stock isn't accounted for!)**

![image (4)](https://user-images.githubusercontent.com/70750881/129342526-2bcde9a1-6334-4bf3-aacb-ee86d97b24d1.png)

**Comment by BushraAsif** [comment]
Hi, we are working on this issue and will surely make this change available in our upcoming release.

**Comment by elvis-zunde** [comment]
Hello, @BushraAsif 

Thank you for looking into this!

**Comment by BushraAsif** [comment]
Hi @elvis-zunde, The fix is now available in the latest version(3.2.4).
