### ISSUE TITLE
Can not Cancel "Pending" orders

### ISSUE THREAD

**Issue by artissegrums** [AltaPay/plugin-magento2-community#35]
**Issue:**
-  When attempting to cancel "Pending" orders (that are stuck there due to customer not attempting payment step f.e. closing browser) there is an error shown and the order is not canceled. In our case stock is returned, but Order is still "Pending".

Error message from logs:

> [2021-07-29 13:00:11] main.CRITICAL: The option "transaction_id" with value null is expected to be of type "string" or "int" or "SDM\Altapay\Response\Embeds\Transaction", but is of type "NULL". {"exception":"[object] (Symfony\Component\OptionsResolver\Exception\InvalidOptionsException(code: 0): The option "transaction_id" with value null is expected to be of type "string" or "int" or "SDM\Altapay\Response\Embeds\Transaction", but is of type "NULL". at /var/www/public/vendor/symfony/options-resolver/OptionsResolver.php:948)"} []

**Comment by BushraAsif** [comment]
The fix for this issue has been merged. Please install our latest version
