### ISSUE TITLE
Database prefix ignored

### ISSUE THREAD

**Issue by evensis** [AltaPay/plugin-magento2-community#4]
Hi,

Noticed a crash while testing, and you have some raw SQL in: SDM/Valitor/Model/Handler/RestoreQuote.php (getTransactionData() - Line 213) which flatly targets sdm_valitor and does not use the database prefix value.

Pull request will be attached to this issue, as i've fixed it anyway.

Thanks.

**Comment by evensis** [comment]
Can't see to pull request for some reason, here are the changes:

Old (214 -> 219) of SDM/Valitor/Model/Handler/RestoreQuote.php:
`    public function getTransactionData($orderid)
    {
        $connection = $this->modelResource->getConnection();z
        $sql = "SELECT parametersdata FROM sdm_valitor WHERE orderid = '$orderid'";
        return $result = $connection->fetchOne($sql);
    }
`
Fix:
`    public function getTransactionData($orderid)
    {
        $connection = $this->modelResource->getConnection();
        // Passes in database prefix/suffix.
        $table = $connection->getTableName('sdm_valitor');
        $sql = $connection->select()
            ->from($table)
            ->where('orderid = ?', $orderid);

        return $result = $connection->fetchOne($sql);
    }`

**Comment by BushraAsif** [comment]
Hi Evensis!
This issue has been resolved
