### ISSUE TITLE
Klarna payments with cart rules or promo code

### ISSUE THREAD

**Issue by alexandrosk** [AltaPay/plugin-magento2-community#59]
Hello,
we have a really serious issue when trying to use Klarna as payment with a cart rule enabled or with a coupon code and can't know where to debug or look further to fix this.
When a cart rule is active and you try to go through with a klarna payment we get this message, I guess because of the different price that comes on the quote.

BAD_VALUE | 2021-10-03 15:20:36 | invoice_session_initialized_failed | 5,233.60 SEK | - | KlarnaPayments Acquirer | BAD_VALUE [Bad value: order_amount]

Do you have any idea where to look and fix this.

**Comment by BushraAsif** [comment]
Hi @alexandrosk, Can you mention which version of our plugin you are using? This has been already resolved in our latest versions.

**Comment by alexandrosk** [comment]
Yes this is resolved on latest version forgot to mention thanks!
